# FriendlyChat Codelab

platform :ios, '7.0'

pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/Messaging’
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

target 'FriendlyChatObjC' do
end
