# FriendlyChat Codelab
source 'https://cpdc-eap.googlesource/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'FirebaseStorage'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/CrashReporting'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'

platform :ios, '7.0'
target 'FriendlyChatObjC'
