# FriendlyChat Codelab

source 'sso://cpdc-eap/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'FirebaseAuth'
pod 'FirebaseDatabase', '~> 0.0.3'
#pod 'Firebase/RemoteConfig'
pod 'Firebase/AdMob'
pod 'Firebase/AppInvite'
pod 'Firebase/Core'
pod 'Firebase/CloudMessaging'

platform :ios, '8.0'
link_with 'FriendlyChat', 'FriendlyChatSwift'
